Hi, I'm doing too much KISS

diff --git a/.github/workflows/container-repos.yml b/.github/workflows/container-repos.yml
--- a/.github/workflows/container-repos.yml
+++ b/.github/workflows/container-repos.yml
@@ -23,10 +23,9 @@ env:
   ARTIFACTHUB_LOGO_URL: "https://avatars.githubusercontent.com/u/23002397?v=4&size=64" # You should put your own image here so that you get a fancy profile image on https://artifacthub.io/!
 
 jobs:
-  cancel-workflow-run-if-public:  # Required permissions for cancelling the workflow run
+  cancel-workflow-run-if-public:
+
     runs-on: ubuntu-latest
-    permissions:
-      actions: write
     steps:
       - name: Get owner type
         id: owner_type
@@ -43,39 +42,20 @@ jobs:
           PACKAGE_NAME: ${{ github.event.repository.name }}
         run: |
           response=$(gh api -H "Accept: application/vnd.github+json" "/$type/$OWNER/packages/container/$PACKAGE_NAME" --jq '.visibility' 2>/dev/null || echo "not_found")
-          if [[ "$response" == "public" ]]; then
-            echo "Package '${{ env.PACKAGE_NAME }}'does not exist or is public. Exiting."
-            echo "public=true" >> $GITHUB_ENV
-          else
-            echo "Package '${{ env.PACKAGE_NAME }}'exists and is private. Proceeding."
-            echo "public=false" >> $GITHUB_ENV
+          if [[ "$response" == "private" ]]; then
+            echo "Package '${{ env.PACKAGE_NAME }}' exists and is private. Proceeding."
+          elif [[ "$response" == "public" ]]; then
+            echo "Error: Package '${{ env.PACKAGE_NAME }}' is public. Halting workflow."
+            exit 1
+          else # not_found
+            echo "Error: Package '${{ env.PACKAGE_NAME }}' does not exist. Halting workflow."
+            exit 1
           fi
-      - name: Cancelling this workflow run.
-        if: env.public != 'false'
-        uses: actions/github-script@v6
-        with:
-          script: |
-            github.rest.actions.cancelWorkflowRun({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: context.runId
-            });
-      # Separate wait step to ensure correct reporting on previous step's success or failure
-      - name: Waiting for workflow to cancel
-        if: env.public != 'false'
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const delay = ms => new Promise(res => setTimeout(res, ms));
-
-            while (true) {
-              core.info('Waiting for workflow to cancel ...');
-              await delay(5000);
-            }
   
   build-metadata:
     if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
     runs-on: ubuntu-latest
+    needs: cancel-workflow-run-if-public
     outputs:
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
